### PR TITLE
Theme fixes

### PR DESCRIPTION
**Pull request by thewaiter**

### CODE REVIEW

**Comment by mbert** [comment]
Thank you!

**Comment by thewaiter** [comment]
Oops, I added also GTK themes. I hope this is not problem for you

Stefan

**Comment by mbert** [comment]
Not at all a problem. The history's a bit of a mess now,  but the GTK theme is highly welcome.

**Comment by thewaiter** [comment]
Yes, GTK is changing too quickly. We had many issues related to missing the new GTK. I had to create all that stuff in oomox editor.

**Pull request merged**
