### PR TITLE
some new fixes

### PR DESCRIPTION
**Pull request by thewaiter**

### CODE REVIEW

**Comment by mbert** [comment]
Cool, thank you! I'll merge this for now and create a release later as soon as I have a chance to try things out (I cannot access my Linux machine atm).

**Comment by mbert** [comment]
I've finally been able to make a release from your contribution, thank you again. Sorry for taking so long, I have just been able to access my Linux machine again today.

**Comment by thewaiter** [comment]
Hello
Just looked at opendesktop site. In changelog I can see version 0.9.2. Apparently bad number. But not a big deal.
Stefan

**Comment by mbert** [comment]
Thank you! Yes, I found that I have probably made a mistake here, too. But I believe (hope) that this is not really going to have any practical impact.

**Pull request merged**
