### PR TITLE
iBar: adjacent label themed

### PR DESCRIPTION
**Pull request by thewaiter**
This is for moksha desktop only. 
BTW, probably my last commit before packaging :)

S

### CODE REVIEW

**Comment by mbert** [comment]
Thank you. I actually package every one of your PRs, as it's nice to get early feedback. In case of problems earlier versions can always be downloaded from here.
    So this one will become 0.9.7.

Since I don't like two digit major, minor and patch versions we will soon be at 1.0.0. Do you think that where we are now would be a good candidate?

**Comment by thewaiter** [comment]
Hmmm, this is fully up to you. Do not think users matter. Anyway I think significant changes were put to this theme last few days. Still beautiful theme worth attention :)

**Comment by mbert** [comment]
> Hmmm, this is fully up to you. Do not think users matter. Anyway I think significant changes were put to this theme last few days. Still beautiful theme worth attention :)

So if you think that you're not going to add anything for now, I can as well make this 1.0.0. I'm currently adding an rpm spec, so that in future I'll also provide rpm packages.

**Comment by mbert** [comment]
@thewaiter  As I am currently in the process of packaging the theme as rpm I have run into a problem, maybe you can help here? When I install the .edj file as a user theme (i.e. import from the file system) it works just fine. However when copying it to /usr/share/elementary/themes, it is displayed without a thumbnail in the list of "system" themes, and when trying to load it, E will fall back to the default (dark) theme. 

Have you got any idea what the problem might be? 

[edit] found the problem. It was permissions.

**Comment by mbert** [comment]
Version bump 1.0.0, release here:
- https://www.pling.com/p/1018484/
- https://github.com/mbert/etheme-blingbling-e20/releases/tag/releases%2F1.0.0

Since you are on Moksha which is a deb-based distribution, maybe you'd like to provide debianisation? I used to work on deb-based systems most of my life but due to my work I'm now on Fedora and hence cannot really test deb packaging here.

**Comment by thewaiter** [comment]
Sure, let me send you link with debianisation:
https://github.com/BodhiDev/Bodhi-themes/tree/master/bodhi-theme-moksha-blingbling

**Comment by thewaiter** [comment]
BTW, my package contains my own icon set created with Oomox. Not sure you included in rpm. It is also for Bodhi users only.

**Comment by mbert** [comment]
> BTW, my package contains my own icon set created with Oomox. Not sure you included in rpm. It is also for Bodhi users only.

In the rpm I have only packaged the theme itself. It's a bit based on what I personally use. But I see no reason to include something else if it makes sense.

**Comment by thewaiter** [comment]
Excelent. It is OK then :)

**Comment by mbert** [comment]
Thank you, I have now created a deb file, you can find it here: https://github.com/mbert/etheme-blingbling-e20/releases/tag/releases%2F1.0.0

I have not been able to try it out though...

**Pull request merged**
